### ISSUE TITLE
Issue running the example.py

### ISSUE THREAD

**Issue by rahuldeo2047** [kyegomez/GPT3#1]
I am beginning to enjoy your repositories.
Thanks for keeping these for the novice learners like us.

I am finding difficulties running example.py can you please help me run?

$ python example.py 

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    model = GPT3()
  File "GPT3/gpt3/gpt3.py", line 17, in __init__
    num_tokens=self.num_tokens,
  File "python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPT3' object has no attribute 'num_tokens'

I also tried RoboCAT that is not working due to my GPU limitations. However, I have both roboCAT and gpt3-torch Installed.

**Comment by kyegomez** [comment]
@rahuldeo2047 Hey thanks for submitting this issue, I have tried my best to fix it but it is quite big and I cannot run it myself!
